### ISSUE TITLE
Access error due to faulty file in the archive [NSFW]

### ISSUE THREAD

**Issue by GamePorter** [madeddy/RpaKit#1]
**Warning this issue is NSFW**

Hey ! I used Rpakit for a month now and it is rock solid but ended up having an issue with a game. It's highly likely that the problem comes from the game but I need to be sure.

Game is https://f95zone.to/threads/rogue-like-evolution-v0-990e-oni.14/

I did
`py .\rpakit.py -e .\game\`
and I got these logs
[logs.txt](https://github.com/madeddy/RpaKit/files/4261963/logs.txt)

**Comment by madeddy** [comment]
Sorry for answering this late. Thanks for bringing this to attention.

I don't think this comes from "rpakit". Look at first like a simple rights problem, but no. It could be in your system the case,(Check admin/user rights) but I get an different pathlib error which makes no sense. (IsADirectoryError: [Errno 21] from pathlib)

It's afaik from the game somehow. Possible another attempt do hide their million dollar files which then anyway are showed if the game runs or a weird issue with the stone age old renpy version. I need to look in the renpy files if there was some stuff played with.

Edit: Confirmed its the games/packages fault. I tested with a different unpacker and it errors with the same message. Question if thats a accidental thing or some ugly, time stealing stuff with python/renpy what they did. Will see.

Edit2:
There is a little file "without" name placed in the archive and this throws correctly a directory error (instead file) in every unarchiver. Like expected: Another of this destructive but nonetheless useless attempts.

Greets
